import {Dimensions} from 'react-native';
import {theme} from '../constants/theme';

export const COMMON_ANIMATION_DURATION = 400;
export const WIDTH = Dimensions.get('window').width;
export const HEIGHT = Dimensions.get('window').height;

export const IS_IPHONE_MINI = () => HEIGHT < 700;

export const MAIN_HORIZONTAL_WIDTH = theme.spacing(3);

export const CATEGORY_ITEMS = [
  {
    imageUrl: require('../assets/category-items/insta.png'),
    name: 'Reels',
    desc: 'Get creative descriptions for your Instagram Reels',
    firstMessage: 'What is your reel about?',
    isPopular: true,
    category: 'Social_media',
    query: 'Create a description for an Instagram Reel about: {text}',
    isLarge: true,
  },
  {
    imageUrl: require('../assets/category-items/facebook.png'),
    name: 'Facebook',
    desc: 'Stand out on Facebook with unique posts',
    firstMessage: 'What do you want the post to be about?',
    isPopular: true,
    category: 'Social_media',
    query: 'Create a Facebook post about: {text}',
  },
  {
    imageUrl: require('../assets/category-items/essay.png'),
    name: 'Essay',
    desc: 'Have a well-structured essay written especially for you',
    firstMessage: 'What’s the topic of your essay?',
    isPopular: true,
    category: 'Education',
    query: 'Write an essay on the following topic: {text}',
  },
  {
    imageUrl: require('../assets/category-items/tiktok.png'),
    name: 'Tiktok',
    desc: 'Boost your TikTok views with appealing captions',
    firstMessage: 'What is your video about?',
    isPopular: true,
    category: 'Social_media',
    query: 'Create an appealing TikTok caption for a video about: {text}',
  },
  {
    imageUrl: require('../assets/category-items/tiktok.png'),
    name: 'Linkedin_profile',
    desc: 'Create memorable posts on LinkedIn',
    firstMessage: 'What do you want the post to be about?',
    category: 'Social_media',
    query: 'Create a LinkedIn post about: {text}',
  },
  {
    imageText: '🔖',
    name: 'Chatting',
    desc: 'Casual conversations on any topic',
    firstMessage: 'Start a chat with AI',
    category: 'Social_media',
    query: 'Start a casual conversation',
  },
  {
    imageUrl: require('../assets/category-items/tiktok.png'),
    name: 'X_profile',
    desc: 'Craft compelling X posts',
    firstMessage: 'What is the topic of your post?',
    category: 'Social_media',
    query: 'Create a compelling X post about: {text}',
    isLarge: true,
  },
  {
    imageUrl: require('../assets/category-items/tiktok.png'),
    name: 'X_posts',
    desc: 'Summarize your text into a short post',
    firstMessage: 'Type the text you want to summarize',
    category: 'Social_media',
    query: 'Summarize the following text into a short X post: {text}',
  },
];

// [
//   //   {
//   //     imageUrl: require('../assets/category-items/textSummary.png'),
//   //     name: 'TEXT_SUMMARY',
//   //     desc: 'Summarize any text and create a numbered list of its key points',
//   //     firstMessage: 'Type the text you want summarized',
//   //     isPopular: true,
//   //     category: 'EDUCATION',
//   //     query: 'Summarize the following text: {text}',
//   //   },
//   //   {
//   //     imageUrl: require('../assets/category-items/writing.png'),
//   //     name: 'WRITING',
//   //     desc: 'Fight writer’s block and finish your text',
//   //     firstMessage: 'Type your unfinished text',
//   //     isPopular: true,
//   //     category: 'EDUCATION',
//   //     query: 'Finish the following text: {text}',
//   //   },
//   //   {
//   //     imageUrl: require('../assets/category-items/rewriting.png'),
//   //     name: 'REWRITING',
//   //     desc: 'Create unique rewrites with high text authenticity',
//   //     firstMessage: 'Type your text',
//   //     isPopular: true,
//   //     category: 'EDUCATION',
//   //     query: 'Rewrite the following text: {text}',
//   //   },
//   //   {
//   //     imageUrl: require('../assets/category-items/textCheck.png'),
//   //     name: 'TEXT_CHECK',
//   //     desc: 'Check any text for spelling and grammatical mistakes',
//   //     firstMessage: 'Type your text',
//   //     isPopular: true,
//   //     category: 'EDUCATION',
//   //     query:
//   //       'Check the following text for spelling and grammatical mistakes: {text}',
//   //   },
//   //   {
//   //     imageUrl: require('../assets/category-items/insta.png'),
//   //     name: 'CONTENT',
//   //     desc: 'Create Instagram posts on any topic',
//   //     firstMessage: 'What do you want the post to be about?',
//   //     isPopular: true,
//   //     category: 'SOCIAL_MEDIA',
//   //     query: 'Create an Instagram post about: {text}',
//   //   },
//   //   {
//   //     imageUrl: require('../assets/category-items/insta.png'),
//   //     name: 'CAPTIONS',
//   //     desc: 'Come up with engaging captions for your Instagram posts',
//   //     firstMessage:
//   //       'Describe the photo in your post in as much detail as possible',
//   //     isPopular: true,
//   //     category: 'SOCIAL_MEDIA',
//   //     query: 'Create an engaging caption for a photo described as: {text}',
//   //   },
//   {
//     imageUrl: require('../assets/category-items/insta.png'),
//     name: 'REELS',
//     desc: 'Get creative descriptions for your Instagram Reels',
//     firstMessage: 'What is your reel about?',
//     isPopular: true,
//     category: 'SOCIAL_MEDIA',
//     query: 'Create a description for an Instagram Reel about: {text}',
//     isLarge: true,
//   },
//   {
//     imageUrl: require('../assets/category-items/facebook.png'),
//     name: 'FACEBOOK',
//     desc: 'Stand out on Facebook with unique posts',
//     firstMessage: 'What do you want the post to be about?',
//     isPopular: true,
//     category: 'SOCIAL_MEDIA',
//     query: 'Create a Facebook post about: {text}',
//   },
//   {
//     imageUrl: require('../assets/category-items/essay.png'),
//     name: 'ESSAY',
//     desc: 'Have a well-structured essay written especially for you',
//     firstMessage: 'What’s the topic of your essay?',
//     isPopular: true,
//     category: 'EDUCATION',
//     query: 'Write an essay on the following topic: {text}',
//   },
//   {
//     imageUrl: require('../assets/category-items/tiktok.png'),
//     name: 'TIKTOK',
//     desc: 'Boost your TikTok views with appealing captions',
//     firstMessage: 'What is your video about?',
//     isPopular: true,
//     category: 'SOCIAL_MEDIA',
//     query: 'Create an appealing TikTok caption for a video about: {text}',
//   },
//   //   {
//   //     imageUrl: require('../assets/category-items/aiArt.png'),
//   //     name: 'AI_ART',
//   //     desc: 'Create detailed prompts you can use in AI image generators',
//   //     firstMessage: 'Describe the image you want to generate',
//   //     isPopular: true,
//   //     category: 'FUN',
//   //     query:
//   //       'Create a detailed AI image prompt for the following description: {text}',
//   //   },
//   //   {
//   //     imageUrl: require('../assets/category-items/reply.png'),
//   //     name: 'REPLY_IDEAS',
//   //     desc: 'Explore possible replies to your partner’s messages',
//   //     firstMessage: 'What did your partner say?',
//   //     isPopular: true,
//   //     category: 'COMMUNICATION',
//   //     query: 'Create a reply to the following message: {text}',
//   //   },
//   //   {
//   //     imageUrl: require('../assets/category-items/textStyle.png'),
//   //     name: 'TEXT_STYLE',
//   //     desc: 'See your text rewritten in another style',
//   //     firstMessage: 'What is the preferred style for the rewritten text?',
//   //     isPopular: true,
//   //     category: 'EDUCATION',
//   //     query: 'Rewrite the following text in the style of {text}',
//   //   },
//   {
//     imageUrl: require('../assets/category-items/tiktok.png'),
//     name: 'TIKTOK',
//     desc: 'Boost your TikTok views with appealing captions',
//     firstMessage: 'What is your video about?',
//     category: 'SOCIAL_MEDIA',
//     query: 'Create an appealing TikTok caption for a video about: {text}',
//   },
//   {
//     imageUrl: require('../assets/category-items/tiktok.png'),
//     name: 'LINKEDIN_PROFILE',
//     desc: 'Create memorable posts on LinkedIn',
//     firstMessage: 'What do you want the post to be about?',
//     category: 'SOCIAL_MEDIA',
//     query: 'Create a LinkedIn post about: {text}',
//   },
//   {
//     imageText: '🔖',
//     name: 'CHATTING',
//     desc: 'Casual conversations on any topic',
//     firstMessage: 'Start a chat with AI',
//     category: 'SOCIAL_MEDIA',
//     query: 'Start a casual conversation',
//   },
//   {
//     imageUrl: require('../assets/category-items/tiktok.png'),
//     name: 'X_PROFILE',
//     desc: 'Craft compelling X posts',
//     firstMessage: 'What is the topic of your post?',
//     category: 'SOCIAL_MEDIA',
//     query: 'Create a compelling X post about: {text}',
//     isLarge: true,
//   },
//   {
//     imageUrl: require('../assets/category-items/tiktok.png'),
//     name: 'X_POSTS',
//     desc: 'Summarize your text into a short post',
//     firstMessage: 'Type the text you want to summarize',
//     category: 'SOCIAL_MEDIA',
//     query: 'Summarize the following text into a short X post: {text}',
//   },
//   //   {
//   //     imageText: '🦹‍♀️',
//   //     name: 'ROLEPLAY',
//   //     desc: 'Talk to AI as if it is someone else',
//   //     firstMessage:
//   //       'What role do you want me to play: your friend, boyfriend, girlfriend, etc.',
//   //     category: 'SOCIAL_MEDIA',
//   //     query: 'Roleplay as {role} and respond to the following: {text}',
//   //   },
//   //   {
//   //     imageText: '😔',
//   //     name: 'THERAPIST',
//   //     desc: 'Get anything off your chest and have a heart-to-heart with AI',
//   //     firstMessage: 'Type whatever feels right',
//   //     category: 'COMMUNICATION',
//   //     query: 'Provide therapeutic support for the following: {text}',
//   //   },
//   //   {
//   //     imageText: '💘',
//   //     name: 'FLIRTING',
//   //     desc: 'Ask engaging questions on your first date',
//   //     firstMessage: "What is your partner's sex?",
//   //     category: 'COMMUNICATION',
//   //     query:
//   //       'Suggest engaging questions for a first date with a partner gender: {text}',
//   //   },
//   //   {
//   //     imageText: '💘',
//   //     name: 'ROMANCE',
//   //     desc: 'Receive romantic date ideas',
//   //     firstMessage: 'What city are you planning your date in?',
//   //     category: 'COMMUNICATION',
//   //     query: 'Suggest romantic date ideas in {text}',
//   //   },
//   //   {
//   //     imageText: '🤖',
//   //     name: 'UNDETECTABLE_AI',
//   //     desc: 'Bypass AI content detectors and make your text plagiarism-free',
//   //     firstMessage: 'Type your text',
//   //     category: 'EDUCATION',
//   //     query:
//   //       'Make the following text undetectable by AI content detectors: {text}',
//   //   },
//   //   {
//   //     imageText: '📏',
//   //     name: 'MATH',
//   //     desc: 'Have any equation solved in a flash',
//   //     firstMessage: 'Type in your equation',
//   //     category: 'EDUCATION',
//   //     query: 'Solve the following equation: {text}',
//   //   },
//   //   {
//   //     name: 'CODING_QUESTIONS',
//   //     imageText: '💻',
//   //     desc: 'Create well-written interview questions',
//   //     firstMessage: 'Which coding language you want?',
//   //     category: 'EDUCATION',
//   //     query:
//   //       'Create a list of 8 questions for my {text} interview. Do not write explanations in replies.',
//   //   },
//   //   {
//   //     name: 'PHYSIC_QUESTIONS',
//   //     imageText: '👩‍🔬',
//   //     desc: 'Create well-written physics questions or problems',
//   //     firstMessage: 'Topic about ....?',
//   //     category: 'EDUCATION',
//   //     query:
//   //       'Create a list of 5 questions or problems about physics class. Topic is {text}. Do not write explanations in replies.',
//   //   },
//   //   {
//   //     name: 'LYRICS',
//   //     imageText: '🎵',
//   //     desc: 'Create the lyrics of a song for any genre of music',
//   //     firstMessage: 'What is this song about?',
//   //     category: 'FUN',
//   //     query:
//   //       'Create the lyrics of a song about {text}. Do not write explanations in replies.',
//   //   },
//   //   {
//   //     name: 'POEM',
//   //     imageText: '📜',
//   //     desc: 'Create poems in different styles',
//   //     firstMessage: 'What is this poem about?',
//   //     category: 'FUN',
//   //     query:
//   //       'Create the poem about {text}. Do not write explanations in replies.',
//   //   },
//   //   {
//   //     name: 'STORY',
//   //     imageText: '📖',
//   //     desc: 'Create a story from a specific topic',
//   //     firstMessage: 'What is this story about?',
//   //     category: 'FUN',
//   //     query:
//   //       'Create the story about {text}. Do not write explanations in replies.',
//   //   },
//   //   {
//   //     name: 'SHORT_FILM',
//   //     imageText: '🎬',
//   //     desc: 'Create a script for a movie',
//   //     firstMessage: 'What is this short film about?',
//   //     category: 'FUN',
//   //     query:
//   //       'Create the short film scenario about {text}. Do not write explanations in replies.',
//   //   },
//   //   {
//   //     name: 'COMPANY_BIO',
//   //     imageText: '📋',
//   //     desc: 'Briefly tell the story of your company',
//   //     firstMessage: 'Company Name and Company aim?',
//   //     category: 'BUSINESS',
//   //     query:
//   //       'Create a company biography. Company name and aim is "{text}". Do not write explanations in replies.',
//   //   },
//   //   {
//   //     name: 'NAME_GENERATOR',
//   //     imageText: '🔖',
//   //     desc: 'Find a great name for your brand or product',
//   //     firstMessage: 'What does your brand/product do?',
//   //     category: 'BUSINESS',
//   //     query:
//   //       'Create an efficient company name. Company aim is {text}. Do not write explanations in replies.',
//   //   },
//   //   {
//   //     name: 'SLOGAN',
//   //     imageText: '📢',
//   //     desc: 'Create a catchy slogan for your business',
//   //     firstMessage: 'What is your business doing?',
//   //     category: 'BUSINESS',
//   //     query:
//   //       'Create a catchy slogan for a business with this emotion {emotion}. Company aim is {text}. Do not write explanations in replies.',
//   //   },
//   //   {
//   //     name: 'ADS',
//   //     imageText: '💫',
//   //     desc: 'Promote a product, service, brand or event',
//   //     firstMessage: 'About what?',
//   //     category: 'BUSINESS',
//   //     query:
//   //       'Create an impressive advertisement text about "{text}". Do not write explanations in replies.',
//   //   },
//   //   {
//   //     name: 'JOB_ADS',
//   //     imageText: '📰',
//   //     desc: 'Write a job description that attracts ideal candidates',
//   //     firstMessage: 'What position are you hiring for?',
//   //     category: 'BUSINESS',
//   //     query:
//   //       'Create a job advertisement. The position is "{text}". Do not write explanations in replies.',
//   //   },
// ];
